# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Jun 19 21:15:00 2019
# ------------------------------------------------

package:
    name: perl-excel-writer-xlsx
    version: '1.00'
source:
    sha256: 3484aa8a74e2c79b789a0483e222dda01d9c8212d645545edd1e4f6e51e26e0c
    url: https://cpan.metacpan.org/authors/id/J/JM/JMCNAMARA/Excel-Writer-XLSX-1.00.tar.gz
build:
    noarch: generic
    number: '0'
    string: pl526_0
requirements:
    host:
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - perl 5.26.2 h516909a_1006
        - perl-app-cpanminus 1.7044 pl526_1
        - perl-archive-zip 1.64 pl526_0
        - perl-carp 1.38 pl526_3
        - perl-compress-raw-zlib 2.086 pl526h6bb024c_1
        - perl-constant 1.33 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-file-path 2.16 pl526_0
        - perl-file-temp 0.2304 pl526_2
        - perl-parent 0.236 pl526_1
        - perl-time-local 1.28 pl526_1
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-archive-zip
        - perl-file-temp
test:
    imports:
        - Excel::Writer::XLSX
        - Excel::Writer::XLSX::Chart
        - Excel::Writer::XLSX::Chart::Area
        - Excel::Writer::XLSX::Chart::Bar
        - Excel::Writer::XLSX::Chart::Column
        - Excel::Writer::XLSX::Chart::Doughnut
        - Excel::Writer::XLSX::Chart::Line
        - Excel::Writer::XLSX::Chart::Pie
        - Excel::Writer::XLSX::Chart::Radar
        - Excel::Writer::XLSX::Chart::Scatter
        - Excel::Writer::XLSX::Chart::Stock
        - Excel::Writer::XLSX::Chartsheet
        - Excel::Writer::XLSX::Drawing
        - Excel::Writer::XLSX::Examples
        - Excel::Writer::XLSX::Format
        - Excel::Writer::XLSX::Package::App
        - Excel::Writer::XLSX::Package::Comments
        - Excel::Writer::XLSX::Package::ContentTypes
        - Excel::Writer::XLSX::Package::Core
        - Excel::Writer::XLSX::Package::Custom
        - Excel::Writer::XLSX::Package::Packager
        - Excel::Writer::XLSX::Package::Relationships
        - Excel::Writer::XLSX::Package::SharedStrings
        - Excel::Writer::XLSX::Package::Styles
        - Excel::Writer::XLSX::Package::Table
        - Excel::Writer::XLSX::Package::Theme
        - Excel::Writer::XLSX::Package::VML
        - Excel::Writer::XLSX::Package::XMLwriter
        - Excel::Writer::XLSX::Shape
        - Excel::Writer::XLSX::Utility
        - Excel::Writer::XLSX::Workbook
        - Excel::Writer::XLSX::Worksheet
about:
    home: http://jmcnamara.github.com/excel-writer-xlsx/
    license: perl_5
    summary: Create a new file in the Excel 2007+ XLSX format.
extra:
    copy_test_source_files: true
    final: true
